version: "3.9"
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ktor123**
      MYSQL_DATABASE: ktor
      MYSQL_USER: ktor
      MYSQL_PASSWORD: Ktor123**
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3316:3306"

  ktor-api:
    build: .
    container_name: ktor-api
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: 'redis:6-alpine'
    platform: linux/x86_64
    ports:
      - "6389:6379"
